name: CI

on:
  push:
    branches-ignore: [gh-pages]
  pull_request:
    branches-ignore: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      Configuration: Release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
      - run: dotnet restore
      - run: dotnet build --no-restore
