on:
  push:
    branches: [ master ]

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - run: dotnet publish -c Release -o bin/publish
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: {{ github.token }}
          publish_dir: ./bin/publish/wwwroot
