name: Deploy to GH pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      PagesCname: gallery.bsdata.net
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
      - run: dotnet publish -c Release -o bin/publish -p:GHPages=true -p:GHPagesBase=https://${{ env.PagesCname }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./bin/publish/wwwroot
          cname: ${{ env.PagesCname }}
          force_orphan: true
